# Importing Libraries

In [1]:
#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import math

# Dataset Loading
This is a dataset about fish and it's some features like length,height.
I have tried to predict the name of the fish from multiple attributes with multiple linear regression.

In [2]:
df = pd.read_csv("Fish.csv")
display(df)

Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...     ...      ...      ...      ...      ...     ...
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

# Exploratory Data Analysis


In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Species  159 non-null    object 
 1   Weight   159 non-null    float64
 2   Length1  159 non-null    float64
 3   Length2  159 non-null    float64
 4   Length3  159 non-null    float64
 5   Height   159 non-null    float64
 6   Width    159 non-null    float64
dtypes: float64(6), object(1)
memory usage: 8.8+ KB


In [4]:
df.describe(include='all')

Species       Weight     Length1     Length2     Length3      Height  \
count      159   159.000000  159.000000  159.000000  159.000000  159.000000   
unique       7          NaN         NaN         NaN         NaN         NaN   
top      Perch          NaN         NaN         NaN         NaN         NaN   
freq        56          NaN         NaN         NaN         NaN         NaN   
mean       NaN   398.326415   26.247170   28.415723   31.227044    8.970994   
std        NaN   357.978317    9.996441   10.716328   11.610246    4.286208   
min        NaN     0.000000    7.500000    8.400000    8.800000    1.728400   
25%        NaN   120.000000   19.050000   21.000000   23.150000    5.944800   
50%        NaN   273.000000   25.200000   27.300000   29.400000    7.786000   
75%        NaN   650.000000   32.700000   35.500000   39.650000   12.365900   
max        NaN  1650.000000   59.000000   63.400000   68.000000   18.957000   

             Width  
count   159.000000  
unique         NaN  
top            NaN  
freq           NaN  
mean      4.417486  
std       1.685804  
min       1.047600  
25%       3.385650  
50%       4.248500  
75%       5.584500  
max       8.142000

In [5]:
df.describe(include=object)

Species
count      159
unique       7
top      Perch
freq        56

In [6]:
df.count()

Species    159
Weight     159
Length1    159
Length2    159
Length3    159
Height     159
Width      159
dtype: int64

In [7]:
df.Species.value_counts()

Perch        56
Bream        35
Roach        20
Pike         17
Smelt        14
Parkki       11
Whitefish     6
Name: Species, dtype: int64

In [25]:
df.corr()

Species    Weight   Length1   Length2   Length3    Height     Width
Species  1.000000  0.066072  0.217057  0.205152  0.200763 -0.186885 -0.143823
Weight   0.066072  1.000000  0.915712  0.918618  0.923044  0.724345  0.886507
Length1  0.217057  0.915712  1.000000  0.999517  0.992031  0.625378  0.867050
Length2  0.205152  0.918618  0.999517  1.000000  0.994103  0.640441  0.873547
Length3  0.200763  0.923044  0.992031  0.994103  1.000000  0.703409  0.878520
Height  -0.186885  0.724345  0.625378  0.640441  0.703409  1.000000  0.792881
Width   -0.143823  0.886507  0.867050  0.873547  0.878520  0.792881  1.000000

In [8]:
df["Species"].replace({"Perch": 1, "Bream": 2,"Roach": 3,"Smelt": 4,"Parkki":5,"Whitefish":6,"Pike":7}, inplace=True)
print(df)

     Species  Weight  Length1  Length2  Length3   Height   Width
0          2   242.0     23.2     25.4     30.0  11.5200  4.0200
1          2   290.0     24.0     26.3     31.2  12.4800  4.3056
2          2   340.0     23.9     26.5     31.1  12.3778  4.6961
3          2   363.0     26.3     29.0     33.5  12.7300  4.4555
4          2   430.0     26.5     29.0     34.0  12.4440  5.1340
..       ...     ...      ...      ...      ...      ...     ...
154        4    12.2     11.5     12.2     13.4   2.0904  1.3936
155        4    13.4     11.7     12.4     13.5   2.4300  1.2690
156        4    12.2     12.1     13.0     13.8   2.2770  1.2558
157        4    19.7     13.2     14.3     15.2   2.8728  2.0672
158        4    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]


In [9]:
for col in df.columns:
    print(df[col].value_counts())

1    56
2    35
3    20
7    17
4    14
5    11
6     6
Name: Species, dtype: int64
300.0     6
500.0     5
120.0     5
700.0     5
1000.0    5
         ..
556.0     1
840.0     1
690.0     1
345.0     1
242.0     1
Name: Weight, Length: 101, dtype: int64
19.0    6
20.0    5
22.0    4
20.5    4
24.0    3
       ..
10.8    1
44.8    1
48.3    1
10.7    1
30.9    1
Name: Length1, Length: 116, dtype: int64
22.0    7
35.0    6
40.0    5
22.5    5
21.0    4
       ..
37.3    1
11.2    1
12.2    1
24.6    1
56.0    1
Name: Length2, Length: 93, dtype: int64
23.5    5
36.2    3
45.5    3
25.0    3
22.5    3
       ..
45.8    1
13.2    1
20.8    1
15.2    1
30.0    1
Name: Length3, Length: 124, dtype: int64
11.1366    2
9.6000     2
2.2139     2
5.6925     2
6.1100     2
          ..
16.3618    1
17.6235    1
11.9328    1
12.6040    1
5.8750     1
Name: Height, Length: 154, dtype: int64
3.5250    3
4.3350    2
3.6240    2
6.1440    2
1.1484    2
         ..
3.7250    1
1.2772    1
5.5800    1
6

In [10]:
print(df.columns)

Index(['Species', 'Weight', 'Length1', 'Length2', 'Length3', 'Height',
       'Width'],
      dtype='object')


In [11]:
X = df[[ 'Weight', 'Length1', 'Length2', 'Length3', 'Height',
       'Width']].values  
#.values is converting dataframe into array
print(X)
y = df[['Species']].values
print(y)

[[2.42000e+02 2.32000e+01 2.54000e+01 3.00000e+01 1.15200e+01 4.02000e+00]
 [2.90000e+02 2.40000e+01 2.63000e+01 3.12000e+01 1.24800e+01 4.30560e+00]
 [3.40000e+02 2.39000e+01 2.65000e+01 3.11000e+01 1.23778e+01 4.69610e+00]
 [3.63000e+02 2.63000e+01 2.90000e+01 3.35000e+01 1.27300e+01 4.45550e+00]
 [4.30000e+02 2.65000e+01 2.90000e+01 3.40000e+01 1.24440e+01 5.13400e+00]
 [4.50000e+02 2.68000e+01 2.97000e+01 3.47000e+01 1.36024e+01 4.92740e+00]
 [5.00000e+02 2.68000e+01 2.97000e+01 3.45000e+01 1.41795e+01 5.27850e+00]
 [3.90000e+02 2.76000e+01 3.00000e+01 3.50000e+01 1.26700e+01 4.69000e+00]
 [4.50000e+02 2.76000e+01 3.00000e+01 3.51000e+01 1.40049e+01 4.84380e+00]
 [5.00000e+02 2.85000e+01 3.07000e+01 3.62000e+01 1.42266e+01 4.95940e+00]
 [4.75000e+02 2.84000e+01 3.10000e+01 3.62000e+01 1.42628e+01 5.10420e+00]
 [5.00000e+02 2.87000e+01 3.10000e+01 3.62000e+01 1.43714e+01 4.81460e+00]
 [5.00000e+02 2.91000e+01 3.15000e+01 3.64000e+01 1.37592e+01 4.36800e+00]
 [3.40000e+02 2.95000e+01

In [12]:
print(y.shape)

(159, 1)


# DATASET SPLITING

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)

In [14]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(127, 6)
(127, 1)
(32, 6)
(32, 1)


# MODEL 

In [15]:
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [16]:
y_pred = model.predict(X_test)

In [24]:
print(X_test[0:1])
sample_predict=model.predict(X_test[0:1])
print(sample_predict)

[[390.    27.6   30.    35.    12.67   4.69]]
[[3.43064931]]


# MODEL EVALUATION

In [ ]:
#Comparison
print('- y_pred : ')
print(y_pred)
print('- y_test : ')
print(y_test)

In [ ]:
print(y_pred.sum().mean())
print(y_test.sum().mean())
print("So called Accuracy ", y_pred.sum().mean()/y_test.sum().mean())

In [ ]:
y_pred/y_test